#!/bin/bash
# SCRIPT
# NAME: myvcs
# DESCRIPTION: This script is the main executible for the myvcs script
#				series. It is the entry point for all script commands,
#				and it will call all the other scripts associated with it.
# OPTIONS:
#			[command] : (Required) The name of the command that this script will execute.
#							Each command calls another script for that specific function.
#			[options...] : (Optional) The various sub-scripts require various amounts of
#							options. What will and won't be required varies depending on
#							which command is used.

# Get the current, starting directory location
CURRENT_DIR=$(pwd)

function configure_myvcs {
	
}

# Try getting the properties file path config file
source ./.myvcs-path.properties 1>/dev/null 2>/dev/null

if [ $? -ne 0 ]; then
	configure_myvcs
else
	echo "Found file"
fi

